### ISSUE TITLE
esp_sntp.h missing

### ISSUE THREAD

**Issue by bobh** [jscatena88/esp_wwvb#1]
/Users/.../Desktop/esp_wwvb-master/main/main.c:‪11:22‬: fatal error: esp_sntp.h: No such file or directory
compilation terminated.

**Comment by jscatena88** [comment]
Hi bobh,

That header file is part of the esp32 sdk. My suspicion is that your environment isn't set up correctly? Have you set up the esp32 toolchain and esp-idf as documented in the espressif documentation?

**Comment by bobh** [comment]
OK, I'll check in to it. 
tnx

**Comment by bobh** [comment]
Jason,

It’s odd. I can compile/flash the Espressif example at 
/Users/bobh/esp/esp-idf/examples/protocols/sntp

But compiling in the clone of your esp_wwvb-master I get that error.
esp_sntp.h is missing.
I’m not that strong at esp-idf and wwdc has started so I’ll have to let it go for now.

Good luck,
bobh
