### ISSUE TITLE
Issue when compiling with ESP-ISF

### ISSUE THREAD

**Issue by rezin8** [jscatena88/esp_wwvb#2]
Jason, I'm trying to get this thing compiled and I'm hitting a brick wall... Here's what I'm getting. Did you run into anything like this?

100%] Built target __idf_wifi_provisioning
[100%] Built target __idf_esp_https_ota
[100%] Built target __idf_esp_local_ctrl
[100%] Built target __idf_main
[100%] Built target __ldgen_output_esp32.project.ld
[100%] Linking CXX executable WWVB.elf
/Users/greg/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/main/libmain.a(main.c.obj):(.literal.modulateTask+0xc): undefined reference to `dac_scale_set'
/Users/greg/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/main/libmain.a(main.c.obj):(.literal.app_main+0x18): undefined reference to `dac_frequency_set'
/Users/greg/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/main/libmain.a(main.c.obj):(.literal.app_main+0x1c): undefined reference to `dac_offset_set'
/Users/greg/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/main/libmain.a(main.c.obj):(.literal.app_main+0x20): undefined reference to `dac_invert_set'
/Users/greg/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/main/libmain.a(main.c.obj):(.literal.app_main+0x24): undefined reference to `dac_cosine_enable'
/Users/greg/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/main/libmain.a(main.c.obj):(.literal.DataGenTask+0x20): undefined reference to `ampEncTime'
/Users/greg/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/main/libmain.a(main.c.obj): in function `modulateTask':
/Users/greg/esp/esp_wwvb-master/main/main.c:53: undefined reference to `dac_scale_set'
/Users/greg/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: /Users/greg/esp/esp_wwvb-master/main/main.c:61: undefined reference to `dac_scale_set'
/Users/greg/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/main/libmain.a(main.c.obj): in function `app_main':
/Users/greg/esp/esp_wwvb-master/main/main.c:159: undefined reference to `dac_frequency_set'
/Users/greg/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: /Users/greg/esp/esp_wwvb-master/main/main.c:159: undefined reference to `dac_scale_set'
/Users/greg/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: /Users/greg/esp/esp_wwvb-master/main/main.c:125: undefined reference to `dac_offset_set'
/Users/greg/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: /Users/greg/esp/esp_wwvb-master/main/main.c:126: undefined reference to `dac_invert_set'
/Users/greg/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: /Users/greg/esp/esp_wwvb-master/main/main.c:126: undefined reference to `dac_cosine_enable'
/Users/greg/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/main/libmain.a(main.c.obj): in function `DataGenTask':
/Users/greg/esp/esp_wwvb-master/main/main.c:87: undefined reference to `ampEncTime'
collect2: error: ld returned 1 exit status
make[2]: *** [WWVB.elf] Error 1
make[1]: *** [CMakeFiles/WWVB.elf.dir/all] Error 2
make: *** [all] Error 2
make failed with exit code 2

**Comment by jscatena88** [comment]
Hi rezin8,

Sorry for the delay in answering this. I haven't seen this issue before. The undefined references are all functions defined in the dac-cosine component. So it would seem that somehow the build system isn't seeing that component or building it. Hopefully that helps.

Jason

**Comment by jscatena88** [comment]
Okay I looked into it a little and setup esp-idf from scratch on a new machine. It looks like since I last was playing with this esp-idf fully transitioned to CMake. I updated things so that they all build now. However this is completely untested other than it being able to compile now. It is giving me a few concerning errors I want to look at when I have more time

**Comment by rezin8** [comment]
No problem. I just wanted to play around with it. I have zero experience with esp-idf, I usually use Arduino IDE, so I'll mess around with what you have now and see what I can get working. Thanks.

**Comment by jscatena88** [comment]
Sounds good let me know if it builds for you and I will close this issue. If you run into other problems after it builds you can make a new issue
